// src/app/dashboard/seguimiento/page.jsx
"use client";

import RandomStudents from "@/components/dashboard/RandomStudents";
import ThesisLayout from "@/components/dashboard/ThesisLayout";

export default function SeguimientoPage() {
  return (
    <ThesisLayout>
      <RandomStudents title="Seguimiento y Alertas" />
    </ThesisLayout>
  );
}

// pages/dashboard/seguimiento/index.vue
﻿<template><ThesisLayout><RandomStudentsTable title="Seguimiento y Alertas" /></ThesisLayout></template>
<script setup>definePageMeta({ middleware: "role" }); import ThesisLayout from "~/components/layout/ThesisLayout.vue"; import RandomStudentsTable from "~/components/dashboard/RandomStudentsTable.vue";</script>
