// src/app/dashboard/indicadores/page.jsx
"use client";

import RandomStudents from "@/components/dashboard/RandomStudents";
import ThesisLayout from "@/components/dashboard/ThesisLayout";

export default function IndicadoresPage() {
  return (
    <ThesisLayout>
      <RandomStudents title="Indicadores Académicos" />
    </ThesisLayout>
  );
}

// pages/dashboard/indicadores/index.vue
﻿<template><ThesisLayout><RandomStudentsTable title="Indicadores Académicos" /></ThesisLayout></template>
<script setup>definePageMeta({ middleware: "role" }); import ThesisLayout from "~/components/layout/ThesisLayout.vue"; import RandomStudentsTable from "~/components/dashboard/RandomStudentsTable.vue";</script>
