// src/components/docente/DocenteMenuLayout.jsx
"use client";

import { useRouter } from "next/navigation";

export default function DocenteMenuLayout({ children }) {
  const router = useRouter();

  const handleLogout = async () => {
    await fetch("/api/auth/logout", { method: "POST" });
    router.push("/");
  };

  return (
    <div className="thesis-shell">
      <aside className="thesis-sidebar">
        <h4>Menu Docente</h4>
        <nav className="thesis-menu">
          <a href="/docente">Panel Docente</a>
          <a href="/docente/notas">Registro de notas</a>
          <a href="/docente/asistencia">Registrar asistencia</a>
          <a href="/docente/consolidado">Consolidado de asistencias</a>
          <a href="/docente/reporte">Reporte de tareas</a>
          <button type="button" className="thesis-menu-button thesis-logout" onClick={handleLogout}>
            Cerrar sesión
          </button>
        </nav>
      </aside>
      <div className="dashboard-shell">{children}</div>
    </div>
  );
}

// components/layout/DocenteMenuLayout.vue
﻿<template>
  <div class="thesis-shell">
    <aside class="thesis-sidebar">
      <h4>Menu Docente</h4>
      <nav class="thesis-menu">
        <NuxtLink to="/docente">Panel Docente</NuxtLink>
        <NuxtLink to="/docente/notas">Registro de notas</NuxtLink>
        <NuxtLink to="/docente/asistencia">Registrar asistencia</NuxtLink>
        <NuxtLink to="/docente/consolidado">Consolidado de asistencias</NuxtLink>
        <NuxtLink to="/docente/reporte">Reporte de tÁreas</NuxtLink>
        <button type="button" class="thesis-menu-button thesis-logout" @click="handleLogout">
          Cerrar sesión
        </button>
      </nav>
    </aside>
    <div class="dashboard-shell">
      <slot />
    </div>
  </div>
</template>

<script setup>
const handleLogout = async () => {
  await $fetch("/api/auth/logout", { method: "POST" });
  await navigateTo("/");
};
</script>
