// pages/docente/notas/index.vue
﻿<template>
  <DocenteMenuLayout>
    <div class="grid cols-2">
      <section class="card">
        <h2>Registro de notas</h2>
        <p class="badge">Carga de calificaciones</p>

        <div class="card" style="padding: 16px; margin-top: 16px;">
          <h3>Registrar nota</h3>
          <form class="grid" @submit.prevent="handleGradeSubmit">
            <select v-model="gradeForm.studentId" class="select" required>
              <option value="">Alumno</option>
              <option v-for="student in students" :key="student.id" :value="student.id">{{ student.name }}</option>
            </select>
            <input v-model="gradeForm.score" class="input" type="number" min="0" max="20" placeholder="Nota" required />
            <select v-model="gradeForm.taskId" class="select">
              <option value="">Sin tÁrea asociada</option>
              <option v-for="task in tasks" :key="task.id" :value="task.id">{{ task.title }}</option>
            </select>
            <textÁrea v-model="gradeForm.comment" class="textÁrea" placeholder="Comentario" />
            <button class="button" type="submit">Guardar nota</button>
          </form>
          <p v-if="status" style="color: var(--muted); margin-top: 8px;">{{ status }}</p>
        </div>
      </section>
    </div>
  </DocenteMenuLayout>
</template>

<script setup>
definePageMeta({ middleware: "role" });
import DocenteMenuLayout from "~/components/layout/DocenteMenuLayout.vue";

const initialGrade = { studentId: "", score: "", comment: "", taskId: "" };
const gradeForm = ref({ ...initialGrade });
const status = ref("");

const { students, tasks, docenteId, loadUsers, loadStudents, refreshTasks } = useDocenteBaseData();

const handleGradeSubmit = async () => {
  if (!docenteId.value) {
    status.value = "Selecciona un docente";
    return;
  }

  status.value = "Guardando nota...";
  try {
    await $fetch("/api/grades", {
      method: "POST",
      body: {
        ...gradeForm.value,
        createdById: docenteId.value
      }
    });

    gradeForm.value = { ...initialGrade };
    status.value = "Nota registrada";
  } catch {
    status.value = "Error al guardar nota";
  }
};

onMounted(async () => {
  await loadUsers();
  await loadStudents();
  await refreshTasks(docenteId.value);
});
</script>

// src/app/docente/notas/page.jsx
"use client";

import { useState } from "react";
import DocenteMenuLayout from "@/components/docente/DocenteMenuLayout";
import { useDocenteBaseData } from "@/components/docente/useDocenteData";

const initialGrade = { studentId: "", score: "", comment: "", taskId: "" };

export default function DocenteNotasPage() {
  const { docentes, students, tasks, docenteId, setDocenteId } = useDocenteBaseData();
  const [gradeForm, setGradeForm] = useState(initialGrade);
  const [status, setStatus] = useState("");

  const handleGradeSubmit = async (event) => {
    event.preventDefault();
    if (!docenteId) {
      setStatus("Selecciona un docente");
      return;
    }

    setStatus("Guardando nota...");
    const res = await fetch("/api/grades", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        ...gradeForm,
        createdById: docenteId,
      }),
    });

    if (!res.ok) {
      setStatus("Error al guardar nota");
      return;
    }

    setGradeForm(initialGrade);
    setStatus("Nota registrada");
  };

  return (
    <DocenteMenuLayout>
      <div className="grid cols-2">
        <section className="card">
        <h2>Registro de notas</h2>
        <p className="badge">Carga de calificaciones</p>

        

        <div className="card" style={{ padding: 16, marginTop: 16 }}>
          <h3>Registrar nota</h3>
          <form className="grid" onSubmit={handleGradeSubmit}>
            <select
              className="select"
              value={gradeForm.studentId}
              onChange={(event) => setGradeForm({ ...gradeForm, studentId: event.target.value })}
              required
            >
              <option value="">Alumno</option>
              {students.map((student) => (
                <option key={student.id} value={student.id}>
                  {student.name}
                </option>
              ))}
            </select>
            <input
              className="input"
              type="number"
              min="0"
              max="20"
              placeholder="Nota"
              value={gradeForm.score}
              onChange={(event) => setGradeForm({ ...gradeForm, score: event.target.value })}
              required
            />
            <select
              className="select"
              value={gradeForm.taskId}
              onChange={(event) => setGradeForm({ ...gradeForm, taskId: event.target.value })}
            >
              <option value="">Sin tarea asociada</option>
              {tasks.map((task) => (
                <option key={task.id} value={task.id}>
                  {task.title}
                </option>
              ))}
            </select>
            <textarea
              className="textarea"
              placeholder="Comentario"
              value={gradeForm.comment}
              onChange={(event) => setGradeForm({ ...gradeForm, comment: event.target.value })}
            />
            <button className="button" type="submit">Guardar nota</button>
          </form>
          {status ? <p style={{ color: "var(--muted)", marginTop: 8 }}>{status}</p> : null}
        </div>
        </section>
      </div>
    </DocenteMenuLayout>
  );
}
