// src/app/dashboard/logro/page.jsx
"use client";

import RandomStudents from "@/components/dashboard/RandomStudents";
import ThesisLayout from "@/components/dashboard/ThesisLayout";

export default function LogroPage() {
  return (
    <ThesisLayout>
      <RandomStudents title="Niveles de Logro por Área" />
    </ThesisLayout>
  );
}

// pages/dashboard/logro/index.vue
﻿<template><ThesisLayout><RandomStudentsTable title="Niveles de Logro por Área" /></ThesisLayout></template>
<script setup>definePageMeta({ middleware: "role" }); import ThesisLayout from "~/components/layout/ThesisLayout.vue"; import RandomStudentsTable from "~/components/dashboard/RandomStudentsTable.vue";</script>
